### ISSUE TITLE
Developer documentation for InvenioRDM

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/thisweek#9]
We made a larger update to the developer documentation on InvenioRDM docs:

- https://inveniordm.docs.cern.ch/develop/

### Table of contents

![Screenshot 2022-01-19 at 09 13 33](https://user-images.githubusercontent.com/1698163/150090347-5a447902-cf94-4b0c-a9e0-1430baf3cdaa.png)

**Comment by max-moser** [comment]
i absolutely love it
